# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b63f39d84bf76a9df33f82044d7db0bbc9ee2a871e5bcd0350a07a89f20ab4afbc5695305f7103103088fd1c3ce6e85d901c6cb72e74a9659fc0d4f20bceb0

test:
  secret_key_base: 07e06b794cf4f9c0f28889f78e45afa0074f3b6f2022cd2b45518905a35bff256ef0d834ac80dd4422dc9ea8fa98a3186d2c8bf1cf38674f457f315f029fa31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
